services:
  chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    ports:
    - "4444:4444"
    shm_size: '2g'
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=true
      - SE_BROWSER_LEFTOVERS_INTERVAL_SECS=1800
      - SE_BROWSER_LEFTOVERS_PROCESSES_SECS=3600
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /dev/shm:/dev/shm
  collector:
    container_name: collector
    image: collector
    build:
      context: ../
      dockerfile: ./BuildTools/dockerfile
    depends_on:
    - chrome
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
    - ../:/app/
