name: Run Docker Compose Collector

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - main
      - master

jobs:
  build_and_start:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-docker-action@v4.3.0

    - name: Setup Docker Compose
      uses: docker/setup-compose-action@v1.2.0
    
    - name: Build and start containers
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        docker compose -f BuildTools/docker-compose.yml up -d
    
    - name: Wait for completed
      run: |
        docker ps
        while [[ $(docker ps | grep collector | wc -l) -eq 0 ]]
        do
          echo "waiting for collector"
        done
        docker ps
        while [[ $(docker ps | grep collector | wc -l) -gt 0 ]]
        do
          docker logs collector
          echo "Not completed yet"
          ls -lat | grep csv
          sleep 30
        done
        docker ps
      
    - name: Commit and push changes
      run: |
        git config --global user.email "${{ github.actor.email }}"
        git config --global user.name "${{ github.actor.name }}"
        git add .
        git commit -m "Generated files from docker compose"
        gh pr create --title "Automated PR from Collector Workflow" --body "This PR is created automatically by the GitHub Actions workflow triggered by ${GITHUB_ACTOR}."